### PR TITLE
feat: collapsible sidebar

### PR DESCRIPTION
**Pull request by thesloppyguy**
UX

Is this what you are looking for in the collapsible sidebar?
/claim https://github.com/penxio/penx/issues/54 0x3CA278236fCdf9a3ED551D7a4714343FBe487c52

### CODE REVIEW

**Comment by 0xzion** [comment]
@thesloppyguy Thx to do this, it will be better if the action icon goes to left-top like below:
image

**Comment by 0xzion** [comment]
And do you have a ETH wallet address? after finishing it, claim bounty with your wallet address like:
image

**Comment by thesloppyguy** [comment]
@0xzion Updated the position for the button.

**Comment by 0xzion** [comment]
@thesloppyguy Please claim bounty in: https://bounty.penx.io/bounties/6fafe367-b5f9-48c7-aa02-a1ef06220eb3
Currently, it's just mock token in Arbitrum sepolia, after you claim it , I'll send 20USDT by my wallet.

**Comment by thesloppyguy** [comment]
@0xzion Sorry for the late replay, I have claimed the bounty. Please check on your end.

**Pull request merged**
